version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: demo_sql
  rust:
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    tty: true
    environment:
      USER: root
    volumes:
      - ./:/rust_sapmle
    depends_on:
      - db
    container_name: demo_rust
